
-- Categories
INSERT INTO CATEGORY VALUES (1, 'Dog');
INSERT INTO CATEGORY VALUES (3, 'Cat');
INSERT INTO CATEGORY VALUES (4, 'Bird');
INSERT INTO CATEGORY VALUES (5, 'Reptile');
INSERT INTO CATEGORY VALUES (6, 'Rodent');
INSERT INTO CATEGORY VALUES (7, 'Horse');

-- Insert some animals for tests
INSERT INTO PET VALUES (S_PET.NEXTVAL, 'Labrador chocolate', 3, 1);
INSERT INTO PET VALUES (S_PET.NEXTVAL, 'Yellow bird', 2, 4);
