
-- Categories
INSERT INTO CATEGORY (ID, NAME) VALUES (1, 'Dog');
INSERT INTO CATEGORY (ID, NAME) VALUES (3, 'Cat');
INSERT INTO CATEGORY (ID, NAME) VALUES (4, 'Bird');
INSERT INTO CATEGORY (ID, NAME) VALUES (5, 'Reptile');
INSERT INTO CATEGORY (ID, NAME) VALUES (6, 'Rodent');
INSERT INTO CATEGORY (ID, NAME) VALUES (7, 'Horse');
INSERT INTO CATEGORY (ID, NAME) VALUES (8, 'Fish');

-- Insert some animals for tests
INSERT INTO PET (ID, NAME, QUANTITY, CAT_ID) VALUES (S_PET.NEXTVAL, 'Labrador chocolate', 3, 1);
INSERT INTO PET (ID, NAME, QUANTITY, CAT_ID) VALUES (S_PET.NEXTVAL, 'Yellow bird', 2, 4);
